Repository elastisys/compliantkubernetes-kubespray, pull requests merged in 2023-01, with the labels that each got.

#249 all: added get-requirements file to standardize terraform
  README.md
  WIP-CHANGELOG.md
  get-requirements.yaml
Labels: documentation, feature

#251 docs: added a script that creates migration document
  WIP-CHANGELOG.md
  migration/README.md
  migration/create-migration-document.sh
  migration/template/upgrade-cluster.md
  release/README.md
Labels: documentation, improvement

#254 bin: fix typos in status messages
  bin/apply.bash
  bin/remove-node.bash
  bin/run-playbook.bash
Labels: improvement, not planned

#256 docs: added prompt to migration doc creation script
  migration/create-migration-document.sh
  release/README.md
Labels: documentation, improvement
